//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_full_version.wsBafar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfXmlElement", Namespace="http://schemas.datacontract.org/2004/07/System.Xml", ItemName="XmlElement")]
    [System.SerializableAttribute()]
    public class ArrayOfXmlElement : System.Collections.Generic.List<System.Xml.Linq.XElement> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsBafar.IServicio_ClickFactura")]
    public interface IServicio_ClickFactura {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ObtenCorreos", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ObtenCorreosResponse")]
        ClickFactura_Facturacion.wsBafar.DatosCorreo ObtenCorreos(ClickFactura_Facturacion.wsBafar.CorreosProv prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ObtenCorreos", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ObtenCorreosResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.DatosCorreo> ObtenCorreosAsync(ClickFactura_Facturacion.wsBafar.CorreosProv prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/FiltroCorreo", ReplyAction="http://tempuri.org/IServicio_ClickFactura/FiltroCorreoResponse")]
        ClickFactura_Facturacion.wsBafar.FiltroCorreo FiltroCorreo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/FiltroCorreo", ReplyAction="http://tempuri.org/IServicio_ClickFactura/FiltroCorreoResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.FiltroCorreo> FiltroCorreoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Valida_Factura", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Valida_FacturaResponse")]
        bool Valida_Factura(string Factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Valida_Factura", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Valida_FacturaResponse")]
        System.Threading.Tasks.Task<bool> Valida_FacturaAsync(string Factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_Proveedores_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_Proveedores_SAPResponse")]
        System.Data.DataSet Get_Proveedores_SAP(ClickFactura_Facturacion.wsBafar.Entrada_SAP Consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_Proveedores_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_Proveedores_SAPResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Proveedores_SAPAsync(ClickFactura_Facturacion.wsBafar.Entrada_SAP Consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Valida_Menu", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Valida_MenuResponse")]
        System.Data.DataSet Valida_Menu(string Usuario, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Valida_Menu", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Valida_MenuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Valida_MenuAsync(string Usuario, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Carga_OrdenesCompra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Carga_OrdenesCompraResponse")]
        System.Data.DataSet Carga_OrdenesCompra(string Num_Provedor, string Num_Sociedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Carga_OrdenesCompra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Carga_OrdenesCompraResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Carga_OrdenesCompraAsync(string Num_Provedor, string Num_Sociedad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Carga_DetalleOrden", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Carga_DetalleOrdenResponse")]
        System.Data.DataSet Carga_DetalleOrden(string OrdenCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Carga_DetalleOrden", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Carga_DetalleOrdenResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Carga_DetalleOrdenAsync(string OrdenCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_OrdenCompra_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_OrdenCompra_SAPResponse")]
        System.Data.DataSet Get_OrdenCompra_SAP(string Proveedor, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_OrdenCompra_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_OrdenCompra_SAPResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_OrdenCompra_SAPAsync(string Proveedor, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_DetalleOrdenCompra_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_DetalleOrdenCompra_SAPResponse")]
        System.Data.DataSet Get_DetalleOrdenCompra_SAP(string Orden_Compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_DetalleOrdenCompra_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_DetalleOrdenCompra_SAPResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_DetalleOrdenCompra_SAPAsync(string Orden_Compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_Recepcion_Facturas_Correo", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_Recepcion_Facturas_CorreoResponse")]
        System.Data.DataSet Get_Recepcion_Facturas_Correo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_Recepcion_Facturas_Correo", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_Recepcion_Facturas_CorreoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Recepcion_Facturas_CorreoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_Pasivo_Clase", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_Pasivo_ClaseResponse")]
        ClickFactura_Facturacion.wsBafar.Pasivo_Generado Get_Pasivo_Clase(ClickFactura_Facturacion.wsBafar.Pasivo_Encabezado Encabezado, ClickFactura_Facturacion.wsBafar.Pasivo_Detalle[] Detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_Pasivo_Clase", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_Pasivo_ClaseResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Pasivo_Generado> Get_Pasivo_ClaseAsync(ClickFactura_Facturacion.wsBafar.Pasivo_Encabezado Encabezado, ClickFactura_Facturacion.wsBafar.Pasivo_Detalle[] Detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_SAP_Prov", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_SAP_ProvResponse")]
        ClickFactura_Facturacion.wsBafar.Cat_Proveedor[] Get_SAP_Prov(string Gpo_Sociedad, string Gpo_Cuentas, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_SAP_Prov", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_SAP_ProvResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Proveedor[]> Get_SAP_ProvAsync(string Gpo_Sociedad, string Gpo_Cuentas, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo_SOC_SRE", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo_SOC_SREResponse")]
        ClickFactura_Facturacion.wsBafar.Resultado_GeneraPasivo_SOC_SRE[] Genera_Pasivo_SOC_SRE(ClickFactura_Facturacion.wsBafar.Genera_Pasivo_SOC_SRE Pasivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo_SOC_SRE", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo_SOC_SREResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Resultado_GeneraPasivo_SOC_SRE[]> Genera_Pasivo_SOC_SREAsync(ClickFactura_Facturacion.wsBafar.Genera_Pasivo_SOC_SRE Pasivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_Parametros_Prov", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_Parametros_ProvResponse")]
        System.Collections.Generic.Dictionary<object, object> Get_Parametros_Prov();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Get_Parametros_Prov", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Get_Parametros_ProvResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<object, object>> Get_Parametros_ProvAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Genera_PasivoResponse")]
        ClickFactura_Facturacion.wsBafar.Pasivo_Generado[] Genera_Pasivo(ClickFactura_Facturacion.wsBafar.Pasivo_Encabezado Cabecera_Pasivo, ClickFactura_Facturacion.wsBafar.Pasivo_Detalle[] Detalle_Pasivo, int tipoPasivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Genera_PasivoResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Pasivo_Generado[]> Genera_PasivoAsync(ClickFactura_Facturacion.wsBafar.Pasivo_Encabezado Cabecera_Pasivo, ClickFactura_Facturacion.wsBafar.Pasivo_Detalle[] Detalle_Pasivo, int tipoPasivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Documentos", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_DocumentosResponse")]
        ClickFactura_Facturacion.wsBafar.Listado_Documentos[] Consulta_Documentos(ClickFactura_Facturacion.wsBafar.Filtro_Documento Filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Documentos", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_DocumentosResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Listado_Documentos[]> Consulta_DocumentosAsync(ClickFactura_Facturacion.wsBafar.Filtro_Documento Filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Proveedores_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Proveedores_SAPResponse")]
        ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Proveedor Consulta_Proveedores_SAP(ClickFactura_Facturacion.wsBafar.Filtro_Get_SAP_Prov Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Proveedores_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Proveedores_SAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Proveedor> Consulta_Proveedores_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_Get_SAP_Prov Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_OrdenesCompra_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_OrdenesCompra_SAPResponse")]
        ClickFactura_Facturacion.wsBafar.Ordenes_Compra[] Consulta_OrdenesCompra_SAP(ClickFactura_Facturacion.wsBafar.Filtro_Get_SAP_Ordenes_Compra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_OrdenesCompra_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_OrdenesCompra_SAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Ordenes_Compra[]> Consulta_OrdenesCompra_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_Get_SAP_Ordenes_Compra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Detalle_OrdenCompra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Detalle_OrdenCompraResponse")]
        ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra Consulta_Detalle_OrdenCompra(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Detalle_OrdenCompra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Detalle_OrdenCompraResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra> Consulta_Detalle_OrdenCompraAsync(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Recepcion_OrdenCompra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Recepcion_OrdenCompraResponse")]
        ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra[] Consulta_Recepcion_OrdenCompra(ClickFactura_Facturacion.wsBafar.Filtro_Recepcion_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Recepcion_OrdenCompra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Recepcion_OrdenCompraResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra[]> Consulta_Recepcion_OrdenCompraAsync(ClickFactura_Facturacion.wsBafar.Filtro_Recepcion_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Pasivo_Consignacion", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Pasivo_ConsignacionResponse")]
        ClickFactura_Facturacion.wsBafar.Resultado_Consignacion Pasivo_Consignacion(ClickFactura_Facturacion.wsBafar.Consignacion Consigna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Pasivo_Consignacion", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Pasivo_ConsignacionResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Resultado_Consignacion> Pasivo_ConsignacionAsync(ClickFactura_Facturacion.wsBafar.Consignacion Consigna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Valida_XML", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Valida_XMLResponse")]
        ClickFactura_Facturacion.wsBafar.Resultado_XML Valida_XML(ClickFactura_Facturacion.wsBafar.Cadena_XML XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Valida_XML", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Valida_XMLResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Resultado_XML> Valida_XMLAsync(ClickFactura_Facturacion.wsBafar.Cadena_XML XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Envia_Correo", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Envia_CorreoResponse")]
        void Envia_Correo(ClickFactura_Facturacion.wsBafar.Configuracion_Email Config, ClickFactura_Facturacion.wsBafar.Datos_Email Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Envia_Correo", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Envia_CorreoResponse")]
        System.Threading.Tasks.Task Envia_CorreoAsync(ClickFactura_Facturacion.wsBafar.Configuracion_Email Config, ClickFactura_Facturacion.wsBafar.Datos_Email Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_TipoCambio_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_TipoCambio_SAPResponse")]
        ClickFactura_Facturacion.wsBafar.Tipo_Cambio[] Consulta_TipoCambio_SAP(ClickFactura_Facturacion.wsBafar.Filtro_TipoCambio Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_TipoCambio_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_TipoCambio_SAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Tipo_Cambio[]> Consulta_TipoCambio_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_TipoCambio Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_TipoCambio", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_TipoCambioResponse")]
        ClickFactura_Facturacion.wsBafar.Tipo_Cambio Mantto_TipoCambio(ClickFactura_Facturacion.wsBafar.Tipo_Cambio TipoCambio, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_TipoCambio", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_TipoCambioResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Tipo_Cambio> Mantto_TipoCambioAsync(ClickFactura_Facturacion.wsBafar.Tipo_Cambio TipoCambio, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_NotaCargo_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_NotaCargo_SAPResponse")]
        ClickFactura_Facturacion.wsBafar.Nota_Cargo[] Consulta_NotaCargo_SAP(ClickFactura_Facturacion.wsBafar.Filtro_NotaCargo Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_NotaCargo_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_NotaCargo_SAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Nota_Cargo[]> Consulta_NotaCargo_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_NotaCargo Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_EstadoCuenta_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_EstadoCuenta_SAPResponse")]
        ClickFactura_Facturacion.wsBafar.Estado_Cuenta_FI[] Consulta_EstadoCuenta_SAP(ClickFactura_Facturacion.wsBafar.Filtro_EdoCuenta_FI Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_EstadoCuenta_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_EstadoCuenta_SAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Estado_Cuenta_FI[]> Consulta_EstadoCuenta_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_EdoCuenta_FI Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Proveedor", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_ProveedorResponse")]
        ClickFactura_Facturacion.wsBafar.Cat_Proveedor Mantto_Proveedor(ClickFactura_Facturacion.wsBafar.Cat_Proveedor Proveedor, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Proveedor", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_ProveedorResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Proveedor> Mantto_ProveedorAsync(ClickFactura_Facturacion.wsBafar.Cat_Proveedor Proveedor, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Sociedad", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_SociedadResponse")]
        ClickFactura_Facturacion.wsBafar.Cat_Sociedad Mantto_Sociedad(ClickFactura_Facturacion.wsBafar.Cat_Sociedad Sociedad, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Sociedad", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_SociedadResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Sociedad> Mantto_SociedadAsync(ClickFactura_Facturacion.wsBafar.Cat_Sociedad Sociedad, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Relacion_Proveedor", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Relacion_ProveedorResponse")]
        ClickFactura_Facturacion.wsBafar.Cat_Relacion_Proveedor Mantto_Relacion_Proveedor(ClickFactura_Facturacion.wsBafar.Cat_Relacion_Proveedor Relacion, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Relacion_Proveedor", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Relacion_ProveedorResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Relacion_Proveedor> Mantto_Relacion_ProveedorAsync(ClickFactura_Facturacion.wsBafar.Cat_Relacion_Proveedor Relacion, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Usuario", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_UsuarioResponse")]
        ClickFactura_Facturacion.wsBafar.Cat_Users Mantto_Usuario(ClickFactura_Facturacion.wsBafar.Cat_Users Usuario, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Usuario", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_UsuarioResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Users> Mantto_UsuarioAsync(ClickFactura_Facturacion.wsBafar.Cat_Users Usuario, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Orden_Compra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Orden_CompraResponse")]
        ClickFactura_Facturacion.wsBafar.Ordenes_Compra Mantto_Orden_Compra(ClickFactura_Facturacion.wsBafar.Ordenes_Compra Orden, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Orden_Compra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Orden_CompraResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Ordenes_Compra> Mantto_Orden_CompraAsync(ClickFactura_Facturacion.wsBafar.Ordenes_Compra Orden, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Detalle_Orden_Compra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Detalle_Orden_CompraResponse")]
        ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra Mantto_Detalle_Orden_Compra(ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra Detalle, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Detalle_Orden_Compra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Detalle_Orden_CompraResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra> Mantto_Detalle_Orden_CompraAsync(ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra Detalle, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Detalle_Orden_Compra_Incrementab" +
            "le", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Detalle_Orden_Compra_Incrementab" +
            "leResponse")]
        ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable Mantto_Detalle_Orden_Compra_Incrementable(ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable Incrementable, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Detalle_Orden_Compra_Incrementab" +
            "le", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Detalle_Orden_Compra_Incrementab" +
            "leResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable> Mantto_Detalle_Orden_Compra_IncrementableAsync(ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable Incrementable, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Recepcion_Orden_Compra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Recepcion_Orden_CompraResponse")]
        ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra Mantto_Recepcion_Orden_Compra(ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra Recepcion, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Mantto_Recepcion_Orden_Compra", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Mantto_Recepcion_Orden_CompraResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra> Mantto_Recepcion_Orden_CompraAsync(ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra Recepcion, string Opcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo_Membresia", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo_MembresiaResponse")]
        ClickFactura_Facturacion.wsBafar.Resultado_Membresia[] Genera_Pasivo_Membresia(ClickFactura_Facturacion.wsBafar.Genera_Pasivo_Membresia_SAP Membresia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo_Membresia", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Genera_Pasivo_MembresiaResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Resultado_Membresia[]> Genera_Pasivo_MembresiaAsync(ClickFactura_Facturacion.wsBafar.Genera_Pasivo_Membresia_SAP Membresia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_NotaCargo_SAPV2", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_NotaCargo_SAPV2Response")]
        ClickFactura_Facturacion.wsBafar.Nota_Cargo[] Consulta_NotaCargo_SAPV2(ClickFactura_Facturacion.wsBafar.Filtro_NotaCargoV2 Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_NotaCargo_SAPV2", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_NotaCargo_SAPV2Response")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Nota_Cargo[]> Consulta_NotaCargo_SAPV2Async(ClickFactura_Facturacion.wsBafar.Filtro_NotaCargoV2 Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ConsultaFacturasVerificadas", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ConsultaFacturasVerificadasResponse")]
        System.Data.DataTable ConsultaFacturasVerificadas(ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasRazonSocial FiltroRS, ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasFactura FiltroFacturas, ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasStatus FiltroStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ConsultaFacturasVerificadas", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ConsultaFacturasVerificadasResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ConsultaFacturasVerificadasAsync(ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasRazonSocial FiltroRS, ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasFactura FiltroFacturas, ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasStatus FiltroStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ConsultaAllProveedoresSAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ConsultaAllProveedoresSAPResponse")]
        ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Proveedor2 ConsultaAllProveedoresSAP(ClickFactura_Facturacion.wsBafar.FiltroGetSAPProvByID FiltroProve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ConsultaAllProveedoresSAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ConsultaAllProveedoresSAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Proveedor2> ConsultaAllProveedoresSAPAsync(ClickFactura_Facturacion.wsBafar.FiltroGetSAPProvByID FiltroProve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ConsultaAllSociedadesSAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ConsultaAllSociedadesSAPResponse")]
        ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Sociedad ConsultaAllSociedadesSAP(ClickFactura_Facturacion.wsBafar.FiltroGetSAPSociedades FiltroProve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ConsultaAllSociedadesSAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ConsultaAllSociedadesSAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Sociedad> ConsultaAllSociedadesSAPAsync(ClickFactura_Facturacion.wsBafar.FiltroGetSAPSociedades FiltroProve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ConsultaAllRelacionesPSSAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ConsultaAllRelacionesPSSAPResponse")]
        ClickFactura_Facturacion.wsBafar.Clase_Intercambio_RelPS ConsultaAllRelacionesPSSAP(ClickFactura_Facturacion.wsBafar.FiltroGetSAPRelPS FiltroRel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/ConsultaAllRelacionesPSSAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/ConsultaAllRelacionesPSSAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_RelPS> ConsultaAllRelacionesPSSAPAsync(ClickFactura_Facturacion.wsBafar.FiltroGetSAPRelPS FiltroRel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Detalle_OrdenCompraMultiple", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Detalle_OrdenCompraMultipleRes" +
            "ponse")]
        ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra Consulta_Detalle_OrdenCompraMultiple(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Detalle_OrdenCompraMultiple", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Detalle_OrdenCompraMultipleRes" +
            "ponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra> Consulta_Detalle_OrdenCompraMultipleAsync(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Recepcion_OrdenCompraMultiples" +
            "", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Recepcion_OrdenCompraMultiples" +
            "Response")]
        ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra[] Consulta_Recepcion_OrdenCompraMultiples(ClickFactura_Facturacion.wsBafar.Filtro_Recepcion_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Recepcion_OrdenCompraMultiples" +
            "", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Recepcion_OrdenCompraMultiples" +
            "Response")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra[]> Consulta_Recepcion_OrdenCompraMultiplesAsync(ClickFactura_Facturacion.wsBafar.Filtro_Recepcion_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Incrementable_OrdenCompraMulti" +
            "ple", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Incrementable_OrdenCompraMulti" +
            "pleResponse")]
        ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra2 Consulta_Incrementable_OrdenCompraMultiple(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Incrementable_OrdenCompraMulti" +
            "ple", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Incrementable_OrdenCompraMulti" +
            "pleResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra2> Consulta_Incrementable_OrdenCompraMultipleAsync(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Incrementable_OrdenCompraMulti" +
            "ple2", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Incrementable_OrdenCompraMulti" +
            "ple2Response")]
        ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable3[] Consulta_Incrementable_OrdenCompraMultiple2(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Incrementable_OrdenCompraMulti" +
            "ple2", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Incrementable_OrdenCompraMulti" +
            "ple2Response")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable3[]> Consulta_Incrementable_OrdenCompraMultiple2Async(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_EstadoCuenta_SAP2", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_EstadoCuenta_SAP2Response")]
        ClickFactura_Facturacion.wsBafar.Estado_Cuenta_FI2[] Consulta_EstadoCuenta_SAP2(ClickFactura_Facturacion.wsBafar.Filtro_EdoCuenta_FI Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_EstadoCuenta_SAP2", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_EstadoCuenta_SAP2Response")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Estado_Cuenta_FI2[]> Consulta_EstadoCuenta_SAP2Async(ClickFactura_Facturacion.wsBafar.Filtro_EdoCuenta_FI Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_NotasCargo_SAP2", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_NotasCargo_SAP2Response")]
        ClickFactura_Facturacion.wsBafar.NotasCargo2[] Consulta_NotasCargo_SAP2(ClickFactura_Facturacion.wsBafar.FiltroNotasCargo2 Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_NotasCargo_SAP2", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_NotasCargo_SAP2Response")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.NotasCargo2[]> Consulta_NotasCargo_SAP2Async(ClickFactura_Facturacion.wsBafar.FiltroNotasCargo2 Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Correos_Proveedores", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Correos_ProveedoresResponse")]
        ClickFactura_Facturacion.wsBafar.InformacionSAP[] Consulta_Correos_Proveedores(string direccionProv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Correos_Proveedores", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Correos_ProveedoresResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.InformacionSAP[]> Consulta_Correos_ProveedoresAsync(string direccionProv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Update_Correos_Proveedores", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Update_Correos_ProveedoresResponse")]
        ClickFactura_Facturacion.wsBafar.InformacionSAP[] Update_Correos_Proveedores(ClickFactura_Facturacion.wsBafar.InformacionSAP[] Datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Update_Correos_Proveedores", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Update_Correos_ProveedoresResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.InformacionSAP[]> Update_Correos_ProveedoresAsync(ClickFactura_Facturacion.wsBafar.InformacionSAP[] Datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/MetodoGeneric", ReplyAction="http://tempuri.org/IServicio_ClickFactura/MetodoGenericResponse")]
        ClickFactura_Facturacion.wsBafar.ModelGeneric[] MetodoGeneric(ClickFactura_Facturacion.wsBafar.FiltroGeneric Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/MetodoGeneric", ReplyAction="http://tempuri.org/IServicio_ClickFactura/MetodoGenericResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.ModelGeneric[]> MetodoGenericAsync(ClickFactura_Facturacion.wsBafar.FiltroGeneric Filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Freight_Order_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Freight_Order_SAPResponse")]
        ClickFactura_Facturacion.wsBafar.ModelGeneric[] Consulta_Freight_Order_SAP(string noFreightOrder, string noProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/Consulta_Freight_Order_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/Consulta_Freight_Order_SAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.ModelGeneric[]> Consulta_Freight_Order_SAPAsync(string noFreightOrder, string noProveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/FreightOrderPasivo_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/FreightOrderPasivo_SAPResponse")]
        ClickFactura_Facturacion.wsBafar.ModelGeneric[][] FreightOrderPasivo_SAP(ClickFactura_Facturacion.wsBafar.ModelGeneric[] lista, ClickFactura_Facturacion.wsBafar.objLeidoFactura[] datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/FreightOrderPasivo_SAP", ReplyAction="http://tempuri.org/IServicio_ClickFactura/FreightOrderPasivo_SAPResponse")]
        System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.ModelGeneric[][]> FreightOrderPasivo_SAPAsync(ClickFactura_Facturacion.wsBafar.ModelGeneric[] lista, ClickFactura_Facturacion.wsBafar.objLeidoFactura[] datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/VerificarFacturaBD", ReplyAction="http://tempuri.org/IServicio_ClickFactura/VerificarFacturaBDResponse")]
        MVC5_full_version.wsBafar.VerificarFacturaBDResponse VerificarFacturaBD(MVC5_full_version.wsBafar.VerificarFacturaBDRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/VerificarFacturaBD", ReplyAction="http://tempuri.org/IServicio_ClickFactura/VerificarFacturaBDResponse")]
        System.Threading.Tasks.Task<MVC5_full_version.wsBafar.VerificarFacturaBDResponse> VerificarFacturaBDAsync(MVC5_full_version.wsBafar.VerificarFacturaBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/RegistrarBitacoraOperaciones", ReplyAction="http://tempuri.org/IServicio_ClickFactura/RegistrarBitacoraOperacionesResponse")]
        void RegistrarBitacoraOperaciones(ClickFactura_Facturacion.wsBafar.T_BitacoraOperaciones operaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio_ClickFactura/RegistrarBitacoraOperaciones", ReplyAction="http://tempuri.org/IServicio_ClickFactura/RegistrarBitacoraOperacionesResponse")]
        System.Threading.Tasks.Task RegistrarBitacoraOperacionesAsync(ClickFactura_Facturacion.wsBafar.T_BitacoraOperaciones operaciones);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarFacturaBD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificarFacturaBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string oc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string rfcReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string numProveedor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sociedad;
        
        public VerificarFacturaBDRequest() {
        }
        
        public VerificarFacturaBDRequest(string oc, string rfcReceptor, string numProveedor, string sociedad) {
            this.oc = oc;
            this.rfcReceptor = rfcReceptor;
            this.numProveedor = numProveedor;
            this.sociedad = sociedad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarFacturaBDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificarFacturaBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool VerificarFacturaBDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensaje;
        
        public VerificarFacturaBDResponse() {
        }
        
        public VerificarFacturaBDResponse(bool VerificarFacturaBDResult, string mensaje) {
            this.VerificarFacturaBDResult = VerificarFacturaBDResult;
            this.mensaje = mensaje;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicio_ClickFacturaChannel : MVC5_full_version.wsBafar.IServicio_ClickFactura, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Servicio_ClickFacturaClient : System.ServiceModel.ClientBase<MVC5_full_version.wsBafar.IServicio_ClickFactura>, MVC5_full_version.wsBafar.IServicio_ClickFactura {
        
        public Servicio_ClickFacturaClient() {
        }
        
        public Servicio_ClickFacturaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Servicio_ClickFacturaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servicio_ClickFacturaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servicio_ClickFacturaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClickFactura_Facturacion.wsBafar.DatosCorreo ObtenCorreos(ClickFactura_Facturacion.wsBafar.CorreosProv prov) {
            return base.Channel.ObtenCorreos(prov);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.DatosCorreo> ObtenCorreosAsync(ClickFactura_Facturacion.wsBafar.CorreosProv prov) {
            return base.Channel.ObtenCorreosAsync(prov);
        }
        
        public ClickFactura_Facturacion.wsBafar.FiltroCorreo FiltroCorreo() {
            return base.Channel.FiltroCorreo();
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.FiltroCorreo> FiltroCorreoAsync() {
            return base.Channel.FiltroCorreoAsync();
        }
        
        public bool Valida_Factura(string Factura) {
            return base.Channel.Valida_Factura(Factura);
        }
        
        public System.Threading.Tasks.Task<bool> Valida_FacturaAsync(string Factura) {
            return base.Channel.Valida_FacturaAsync(Factura);
        }
        
        public System.Data.DataSet Get_Proveedores_SAP(ClickFactura_Facturacion.wsBafar.Entrada_SAP Consulta) {
            return base.Channel.Get_Proveedores_SAP(Consulta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Proveedores_SAPAsync(ClickFactura_Facturacion.wsBafar.Entrada_SAP Consulta) {
            return base.Channel.Get_Proveedores_SAPAsync(Consulta);
        }
        
        public System.Data.DataSet Valida_Menu(string Usuario, string Password) {
            return base.Channel.Valida_Menu(Usuario, Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Valida_MenuAsync(string Usuario, string Password) {
            return base.Channel.Valida_MenuAsync(Usuario, Password);
        }
        
        public System.Data.DataSet Carga_OrdenesCompra(string Num_Provedor, string Num_Sociedad) {
            return base.Channel.Carga_OrdenesCompra(Num_Provedor, Num_Sociedad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Carga_OrdenesCompraAsync(string Num_Provedor, string Num_Sociedad) {
            return base.Channel.Carga_OrdenesCompraAsync(Num_Provedor, Num_Sociedad);
        }
        
        public System.Data.DataSet Carga_DetalleOrden(string OrdenCompra) {
            return base.Channel.Carga_DetalleOrden(OrdenCompra);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Carga_DetalleOrdenAsync(string OrdenCompra) {
            return base.Channel.Carga_DetalleOrdenAsync(OrdenCompra);
        }
        
        public System.Data.DataSet Get_OrdenCompra_SAP(string Proveedor, string Fecha) {
            return base.Channel.Get_OrdenCompra_SAP(Proveedor, Fecha);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_OrdenCompra_SAPAsync(string Proveedor, string Fecha) {
            return base.Channel.Get_OrdenCompra_SAPAsync(Proveedor, Fecha);
        }
        
        public System.Data.DataSet Get_DetalleOrdenCompra_SAP(string Orden_Compra) {
            return base.Channel.Get_DetalleOrdenCompra_SAP(Orden_Compra);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_DetalleOrdenCompra_SAPAsync(string Orden_Compra) {
            return base.Channel.Get_DetalleOrdenCompra_SAPAsync(Orden_Compra);
        }
        
        public System.Data.DataSet Get_Recepcion_Facturas_Correo() {
            return base.Channel.Get_Recepcion_Facturas_Correo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Recepcion_Facturas_CorreoAsync() {
            return base.Channel.Get_Recepcion_Facturas_CorreoAsync();
        }
        
        public ClickFactura_Facturacion.wsBafar.Pasivo_Generado Get_Pasivo_Clase(ClickFactura_Facturacion.wsBafar.Pasivo_Encabezado Encabezado, ClickFactura_Facturacion.wsBafar.Pasivo_Detalle[] Detalle) {
            return base.Channel.Get_Pasivo_Clase(Encabezado, Detalle);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Pasivo_Generado> Get_Pasivo_ClaseAsync(ClickFactura_Facturacion.wsBafar.Pasivo_Encabezado Encabezado, ClickFactura_Facturacion.wsBafar.Pasivo_Detalle[] Detalle) {
            return base.Channel.Get_Pasivo_ClaseAsync(Encabezado, Detalle);
        }
        
        public ClickFactura_Facturacion.wsBafar.Cat_Proveedor[] Get_SAP_Prov(string Gpo_Sociedad, string Gpo_Cuentas, string Fecha) {
            return base.Channel.Get_SAP_Prov(Gpo_Sociedad, Gpo_Cuentas, Fecha);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Proveedor[]> Get_SAP_ProvAsync(string Gpo_Sociedad, string Gpo_Cuentas, string Fecha) {
            return base.Channel.Get_SAP_ProvAsync(Gpo_Sociedad, Gpo_Cuentas, Fecha);
        }
        
        public ClickFactura_Facturacion.wsBafar.Resultado_GeneraPasivo_SOC_SRE[] Genera_Pasivo_SOC_SRE(ClickFactura_Facturacion.wsBafar.Genera_Pasivo_SOC_SRE Pasivo) {
            return base.Channel.Genera_Pasivo_SOC_SRE(Pasivo);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Resultado_GeneraPasivo_SOC_SRE[]> Genera_Pasivo_SOC_SREAsync(ClickFactura_Facturacion.wsBafar.Genera_Pasivo_SOC_SRE Pasivo) {
            return base.Channel.Genera_Pasivo_SOC_SREAsync(Pasivo);
        }
        
        public System.Collections.Generic.Dictionary<object, object> Get_Parametros_Prov() {
            return base.Channel.Get_Parametros_Prov();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<object, object>> Get_Parametros_ProvAsync() {
            return base.Channel.Get_Parametros_ProvAsync();
        }
        
        public ClickFactura_Facturacion.wsBafar.Pasivo_Generado[] Genera_Pasivo(ClickFactura_Facturacion.wsBafar.Pasivo_Encabezado Cabecera_Pasivo, ClickFactura_Facturacion.wsBafar.Pasivo_Detalle[] Detalle_Pasivo, int tipoPasivo) {
            return base.Channel.Genera_Pasivo(Cabecera_Pasivo, Detalle_Pasivo, tipoPasivo);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Pasivo_Generado[]> Genera_PasivoAsync(ClickFactura_Facturacion.wsBafar.Pasivo_Encabezado Cabecera_Pasivo, ClickFactura_Facturacion.wsBafar.Pasivo_Detalle[] Detalle_Pasivo, int tipoPasivo) {
            return base.Channel.Genera_PasivoAsync(Cabecera_Pasivo, Detalle_Pasivo, tipoPasivo);
        }
        
        public ClickFactura_Facturacion.wsBafar.Listado_Documentos[] Consulta_Documentos(ClickFactura_Facturacion.wsBafar.Filtro_Documento Filtros) {
            return base.Channel.Consulta_Documentos(Filtros);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Listado_Documentos[]> Consulta_DocumentosAsync(ClickFactura_Facturacion.wsBafar.Filtro_Documento Filtros) {
            return base.Channel.Consulta_DocumentosAsync(Filtros);
        }
        
        public ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Proveedor Consulta_Proveedores_SAP(ClickFactura_Facturacion.wsBafar.Filtro_Get_SAP_Prov Filtro) {
            return base.Channel.Consulta_Proveedores_SAP(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Proveedor> Consulta_Proveedores_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_Get_SAP_Prov Filtro) {
            return base.Channel.Consulta_Proveedores_SAPAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Ordenes_Compra[] Consulta_OrdenesCompra_SAP(ClickFactura_Facturacion.wsBafar.Filtro_Get_SAP_Ordenes_Compra Filtro) {
            return base.Channel.Consulta_OrdenesCompra_SAP(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Ordenes_Compra[]> Consulta_OrdenesCompra_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_Get_SAP_Ordenes_Compra Filtro) {
            return base.Channel.Consulta_OrdenesCompra_SAPAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra Consulta_Detalle_OrdenCompra(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro) {
            return base.Channel.Consulta_Detalle_OrdenCompra(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra> Consulta_Detalle_OrdenCompraAsync(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro) {
            return base.Channel.Consulta_Detalle_OrdenCompraAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra[] Consulta_Recepcion_OrdenCompra(ClickFactura_Facturacion.wsBafar.Filtro_Recepcion_OrdenCompra Filtro) {
            return base.Channel.Consulta_Recepcion_OrdenCompra(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra[]> Consulta_Recepcion_OrdenCompraAsync(ClickFactura_Facturacion.wsBafar.Filtro_Recepcion_OrdenCompra Filtro) {
            return base.Channel.Consulta_Recepcion_OrdenCompraAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Resultado_Consignacion Pasivo_Consignacion(ClickFactura_Facturacion.wsBafar.Consignacion Consigna) {
            return base.Channel.Pasivo_Consignacion(Consigna);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Resultado_Consignacion> Pasivo_ConsignacionAsync(ClickFactura_Facturacion.wsBafar.Consignacion Consigna) {
            return base.Channel.Pasivo_ConsignacionAsync(Consigna);
        }
        
        public ClickFactura_Facturacion.wsBafar.Resultado_XML Valida_XML(ClickFactura_Facturacion.wsBafar.Cadena_XML XML) {
            return base.Channel.Valida_XML(XML);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Resultado_XML> Valida_XMLAsync(ClickFactura_Facturacion.wsBafar.Cadena_XML XML) {
            return base.Channel.Valida_XMLAsync(XML);
        }
        
        public void Envia_Correo(ClickFactura_Facturacion.wsBafar.Configuracion_Email Config, ClickFactura_Facturacion.wsBafar.Datos_Email Correo) {
            base.Channel.Envia_Correo(Config, Correo);
        }
        
        public System.Threading.Tasks.Task Envia_CorreoAsync(ClickFactura_Facturacion.wsBafar.Configuracion_Email Config, ClickFactura_Facturacion.wsBafar.Datos_Email Correo) {
            return base.Channel.Envia_CorreoAsync(Config, Correo);
        }
        
        public ClickFactura_Facturacion.wsBafar.Tipo_Cambio[] Consulta_TipoCambio_SAP(ClickFactura_Facturacion.wsBafar.Filtro_TipoCambio Filtro) {
            return base.Channel.Consulta_TipoCambio_SAP(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Tipo_Cambio[]> Consulta_TipoCambio_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_TipoCambio Filtro) {
            return base.Channel.Consulta_TipoCambio_SAPAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Tipo_Cambio Mantto_TipoCambio(ClickFactura_Facturacion.wsBafar.Tipo_Cambio TipoCambio, string Opcion) {
            return base.Channel.Mantto_TipoCambio(TipoCambio, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Tipo_Cambio> Mantto_TipoCambioAsync(ClickFactura_Facturacion.wsBafar.Tipo_Cambio TipoCambio, string Opcion) {
            return base.Channel.Mantto_TipoCambioAsync(TipoCambio, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Nota_Cargo[] Consulta_NotaCargo_SAP(ClickFactura_Facturacion.wsBafar.Filtro_NotaCargo Filtro) {
            return base.Channel.Consulta_NotaCargo_SAP(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Nota_Cargo[]> Consulta_NotaCargo_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_NotaCargo Filtro) {
            return base.Channel.Consulta_NotaCargo_SAPAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Estado_Cuenta_FI[] Consulta_EstadoCuenta_SAP(ClickFactura_Facturacion.wsBafar.Filtro_EdoCuenta_FI Filtro) {
            return base.Channel.Consulta_EstadoCuenta_SAP(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Estado_Cuenta_FI[]> Consulta_EstadoCuenta_SAPAsync(ClickFactura_Facturacion.wsBafar.Filtro_EdoCuenta_FI Filtro) {
            return base.Channel.Consulta_EstadoCuenta_SAPAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Cat_Proveedor Mantto_Proveedor(ClickFactura_Facturacion.wsBafar.Cat_Proveedor Proveedor, string Opcion) {
            return base.Channel.Mantto_Proveedor(Proveedor, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Proveedor> Mantto_ProveedorAsync(ClickFactura_Facturacion.wsBafar.Cat_Proveedor Proveedor, string Opcion) {
            return base.Channel.Mantto_ProveedorAsync(Proveedor, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Cat_Sociedad Mantto_Sociedad(ClickFactura_Facturacion.wsBafar.Cat_Sociedad Sociedad, string Opcion) {
            return base.Channel.Mantto_Sociedad(Sociedad, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Sociedad> Mantto_SociedadAsync(ClickFactura_Facturacion.wsBafar.Cat_Sociedad Sociedad, string Opcion) {
            return base.Channel.Mantto_SociedadAsync(Sociedad, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Cat_Relacion_Proveedor Mantto_Relacion_Proveedor(ClickFactura_Facturacion.wsBafar.Cat_Relacion_Proveedor Relacion, string Opcion) {
            return base.Channel.Mantto_Relacion_Proveedor(Relacion, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Relacion_Proveedor> Mantto_Relacion_ProveedorAsync(ClickFactura_Facturacion.wsBafar.Cat_Relacion_Proveedor Relacion, string Opcion) {
            return base.Channel.Mantto_Relacion_ProveedorAsync(Relacion, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Cat_Users Mantto_Usuario(ClickFactura_Facturacion.wsBafar.Cat_Users Usuario, string Opcion) {
            return base.Channel.Mantto_Usuario(Usuario, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Cat_Users> Mantto_UsuarioAsync(ClickFactura_Facturacion.wsBafar.Cat_Users Usuario, string Opcion) {
            return base.Channel.Mantto_UsuarioAsync(Usuario, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Ordenes_Compra Mantto_Orden_Compra(ClickFactura_Facturacion.wsBafar.Ordenes_Compra Orden, string Opcion) {
            return base.Channel.Mantto_Orden_Compra(Orden, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Ordenes_Compra> Mantto_Orden_CompraAsync(ClickFactura_Facturacion.wsBafar.Ordenes_Compra Orden, string Opcion) {
            return base.Channel.Mantto_Orden_CompraAsync(Orden, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra Mantto_Detalle_Orden_Compra(ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra Detalle, string Opcion) {
            return base.Channel.Mantto_Detalle_Orden_Compra(Detalle, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra> Mantto_Detalle_Orden_CompraAsync(ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra Detalle, string Opcion) {
            return base.Channel.Mantto_Detalle_Orden_CompraAsync(Detalle, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable Mantto_Detalle_Orden_Compra_Incrementable(ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable Incrementable, string Opcion) {
            return base.Channel.Mantto_Detalle_Orden_Compra_Incrementable(Incrementable, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable> Mantto_Detalle_Orden_Compra_IncrementableAsync(ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable Incrementable, string Opcion) {
            return base.Channel.Mantto_Detalle_Orden_Compra_IncrementableAsync(Incrementable, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra Mantto_Recepcion_Orden_Compra(ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra Recepcion, string Opcion) {
            return base.Channel.Mantto_Recepcion_Orden_Compra(Recepcion, Opcion);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra> Mantto_Recepcion_Orden_CompraAsync(ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra Recepcion, string Opcion) {
            return base.Channel.Mantto_Recepcion_Orden_CompraAsync(Recepcion, Opcion);
        }
        
        public ClickFactura_Facturacion.wsBafar.Resultado_Membresia[] Genera_Pasivo_Membresia(ClickFactura_Facturacion.wsBafar.Genera_Pasivo_Membresia_SAP Membresia) {
            return base.Channel.Genera_Pasivo_Membresia(Membresia);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Resultado_Membresia[]> Genera_Pasivo_MembresiaAsync(ClickFactura_Facturacion.wsBafar.Genera_Pasivo_Membresia_SAP Membresia) {
            return base.Channel.Genera_Pasivo_MembresiaAsync(Membresia);
        }
        
        public ClickFactura_Facturacion.wsBafar.Nota_Cargo[] Consulta_NotaCargo_SAPV2(ClickFactura_Facturacion.wsBafar.Filtro_NotaCargoV2 Filtro) {
            return base.Channel.Consulta_NotaCargo_SAPV2(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Nota_Cargo[]> Consulta_NotaCargo_SAPV2Async(ClickFactura_Facturacion.wsBafar.Filtro_NotaCargoV2 Filtro) {
            return base.Channel.Consulta_NotaCargo_SAPV2Async(Filtro);
        }
        
        public System.Data.DataTable ConsultaFacturasVerificadas(ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasRazonSocial FiltroRS, ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasFactura FiltroFacturas, ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasStatus FiltroStatus) {
            return base.Channel.ConsultaFacturasVerificadas(FiltroRS, FiltroFacturas, FiltroStatus);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ConsultaFacturasVerificadasAsync(ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasRazonSocial FiltroRS, ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasFactura FiltroFacturas, ClickFactura_Facturacion.wsBafar.FiltroFacturasVerificadasStatus FiltroStatus) {
            return base.Channel.ConsultaFacturasVerificadasAsync(FiltroRS, FiltroFacturas, FiltroStatus);
        }
        
        public ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Proveedor2 ConsultaAllProveedoresSAP(ClickFactura_Facturacion.wsBafar.FiltroGetSAPProvByID FiltroProve) {
            return base.Channel.ConsultaAllProveedoresSAP(FiltroProve);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Proveedor2> ConsultaAllProveedoresSAPAsync(ClickFactura_Facturacion.wsBafar.FiltroGetSAPProvByID FiltroProve) {
            return base.Channel.ConsultaAllProveedoresSAPAsync(FiltroProve);
        }
        
        public ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Sociedad ConsultaAllSociedadesSAP(ClickFactura_Facturacion.wsBafar.FiltroGetSAPSociedades FiltroProve) {
            return base.Channel.ConsultaAllSociedadesSAP(FiltroProve);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Sociedad> ConsultaAllSociedadesSAPAsync(ClickFactura_Facturacion.wsBafar.FiltroGetSAPSociedades FiltroProve) {
            return base.Channel.ConsultaAllSociedadesSAPAsync(FiltroProve);
        }
        
        public ClickFactura_Facturacion.wsBafar.Clase_Intercambio_RelPS ConsultaAllRelacionesPSSAP(ClickFactura_Facturacion.wsBafar.FiltroGetSAPRelPS FiltroRel) {
            return base.Channel.ConsultaAllRelacionesPSSAP(FiltroRel);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_RelPS> ConsultaAllRelacionesPSSAPAsync(ClickFactura_Facturacion.wsBafar.FiltroGetSAPRelPS FiltroRel) {
            return base.Channel.ConsultaAllRelacionesPSSAPAsync(FiltroRel);
        }
        
        public ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra Consulta_Detalle_OrdenCompraMultiple(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro) {
            return base.Channel.Consulta_Detalle_OrdenCompraMultiple(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra> Consulta_Detalle_OrdenCompraMultipleAsync(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro) {
            return base.Channel.Consulta_Detalle_OrdenCompraMultipleAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra[] Consulta_Recepcion_OrdenCompraMultiples(ClickFactura_Facturacion.wsBafar.Filtro_Recepcion_OrdenCompra Filtro) {
            return base.Channel.Consulta_Recepcion_OrdenCompraMultiples(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Recepion_OrdenCompra[]> Consulta_Recepcion_OrdenCompraMultiplesAsync(ClickFactura_Facturacion.wsBafar.Filtro_Recepcion_OrdenCompra Filtro) {
            return base.Channel.Consulta_Recepcion_OrdenCompraMultiplesAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra2 Consulta_Incrementable_OrdenCompraMultiple(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro) {
            return base.Channel.Consulta_Incrementable_OrdenCompraMultiple(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Clase_Intercambio_Detalle_OrdenCompra2> Consulta_Incrementable_OrdenCompraMultipleAsync(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro) {
            return base.Channel.Consulta_Incrementable_OrdenCompraMultipleAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable3[] Consulta_Incrementable_OrdenCompraMultiple2(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro) {
            return base.Channel.Consulta_Incrementable_OrdenCompraMultiple2(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Detalle_OrdenCompra_Incrementable3[]> Consulta_Incrementable_OrdenCompraMultiple2Async(ClickFactura_Facturacion.wsBafar.Filtro_Detalle_OrdenCompra Filtro) {
            return base.Channel.Consulta_Incrementable_OrdenCompraMultiple2Async(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.Estado_Cuenta_FI2[] Consulta_EstadoCuenta_SAP2(ClickFactura_Facturacion.wsBafar.Filtro_EdoCuenta_FI Filtro) {
            return base.Channel.Consulta_EstadoCuenta_SAP2(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.Estado_Cuenta_FI2[]> Consulta_EstadoCuenta_SAP2Async(ClickFactura_Facturacion.wsBafar.Filtro_EdoCuenta_FI Filtro) {
            return base.Channel.Consulta_EstadoCuenta_SAP2Async(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.NotasCargo2[] Consulta_NotasCargo_SAP2(ClickFactura_Facturacion.wsBafar.FiltroNotasCargo2 Filtro) {
            return base.Channel.Consulta_NotasCargo_SAP2(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.NotasCargo2[]> Consulta_NotasCargo_SAP2Async(ClickFactura_Facturacion.wsBafar.FiltroNotasCargo2 Filtro) {
            return base.Channel.Consulta_NotasCargo_SAP2Async(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.InformacionSAP[] Consulta_Correos_Proveedores(string direccionProv) {
            return base.Channel.Consulta_Correos_Proveedores(direccionProv);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.InformacionSAP[]> Consulta_Correos_ProveedoresAsync(string direccionProv) {
            return base.Channel.Consulta_Correos_ProveedoresAsync(direccionProv);
        }
        
        public ClickFactura_Facturacion.wsBafar.InformacionSAP[] Update_Correos_Proveedores(ClickFactura_Facturacion.wsBafar.InformacionSAP[] Datos) {
            return base.Channel.Update_Correos_Proveedores(Datos);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.InformacionSAP[]> Update_Correos_ProveedoresAsync(ClickFactura_Facturacion.wsBafar.InformacionSAP[] Datos) {
            return base.Channel.Update_Correos_ProveedoresAsync(Datos);
        }
        
        public ClickFactura_Facturacion.wsBafar.ModelGeneric[] MetodoGeneric(ClickFactura_Facturacion.wsBafar.FiltroGeneric Filtro) {
            return base.Channel.MetodoGeneric(Filtro);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.ModelGeneric[]> MetodoGenericAsync(ClickFactura_Facturacion.wsBafar.FiltroGeneric Filtro) {
            return base.Channel.MetodoGenericAsync(Filtro);
        }
        
        public ClickFactura_Facturacion.wsBafar.ModelGeneric[] Consulta_Freight_Order_SAP(string noFreightOrder, string noProveedor) {
            return base.Channel.Consulta_Freight_Order_SAP(noFreightOrder, noProveedor);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.ModelGeneric[]> Consulta_Freight_Order_SAPAsync(string noFreightOrder, string noProveedor) {
            return base.Channel.Consulta_Freight_Order_SAPAsync(noFreightOrder, noProveedor);
        }
        
        public ClickFactura_Facturacion.wsBafar.ModelGeneric[][] FreightOrderPasivo_SAP(ClickFactura_Facturacion.wsBafar.ModelGeneric[] lista, ClickFactura_Facturacion.wsBafar.objLeidoFactura[] datos) {
            return base.Channel.FreightOrderPasivo_SAP(lista, datos);
        }
        
        public System.Threading.Tasks.Task<ClickFactura_Facturacion.wsBafar.ModelGeneric[][]> FreightOrderPasivo_SAPAsync(ClickFactura_Facturacion.wsBafar.ModelGeneric[] lista, ClickFactura_Facturacion.wsBafar.objLeidoFactura[] datos) {
            return base.Channel.FreightOrderPasivo_SAPAsync(lista, datos);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC5_full_version.wsBafar.VerificarFacturaBDResponse MVC5_full_version.wsBafar.IServicio_ClickFactura.VerificarFacturaBD(MVC5_full_version.wsBafar.VerificarFacturaBDRequest request) {
            return base.Channel.VerificarFacturaBD(request);
        }
        
        public bool VerificarFacturaBD(string oc, string rfcReceptor, string numProveedor, string sociedad, out string mensaje) {
            MVC5_full_version.wsBafar.VerificarFacturaBDRequest inValue = new MVC5_full_version.wsBafar.VerificarFacturaBDRequest();
            inValue.oc = oc;
            inValue.rfcReceptor = rfcReceptor;
            inValue.numProveedor = numProveedor;
            inValue.sociedad = sociedad;
            MVC5_full_version.wsBafar.VerificarFacturaBDResponse retVal = ((MVC5_full_version.wsBafar.IServicio_ClickFactura)(this)).VerificarFacturaBD(inValue);
            mensaje = retVal.mensaje;
            return retVal.VerificarFacturaBDResult;
        }
        
        public System.Threading.Tasks.Task<MVC5_full_version.wsBafar.VerificarFacturaBDResponse> VerificarFacturaBDAsync(MVC5_full_version.wsBafar.VerificarFacturaBDRequest request) {
            return base.Channel.VerificarFacturaBDAsync(request);
        }
        
        public void RegistrarBitacoraOperaciones(ClickFactura_Facturacion.wsBafar.T_BitacoraOperaciones operaciones) {
            base.Channel.RegistrarBitacoraOperaciones(operaciones);
        }
        
        public System.Threading.Tasks.Task RegistrarBitacoraOperacionesAsync(ClickFactura_Facturacion.wsBafar.T_BitacoraOperaciones operaciones) {
            return base.Channel.RegistrarBitacoraOperacionesAsync(operaciones);
        }
    }
}
